### ISSUE TITLE
confused with storage file.

### ISSUE THREAD

**Issue by wordpress-lab** [taviroquai/Laravel-Mapserver#2]
sir i don't understand this.
  storage_path('default.map'),
  storage_path('template.html')

**Comment by taviroquai** [comment]
Hi,

storage_path is a Laravel function to return a storage path.
Please see Laravel documentation.

For example:

If storage folder is /app/storage
then
storage_path('default.map')
is
/app/storage/default.map

If the file does not exists, it will attempt to create it.

**Comment by wordpress-lab** [comment]
thank you
